# Generated by Django 4.2.5 on 2024-02-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pLen', models.IntegerField()),
                ('interval', models.IntegerField()),
                ('count', models.IntegerField()),
                ('bulb', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('save', models.BooleanField(default=False)),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.type')),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.settings')),
            ],
        ),
    ]
