# Generated by Django 4.2.5 on 2024-02-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='intervalSeconds',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='pLenSeconds',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
