# Generated by Django 4.2.5 on 2024-02-29 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_settings_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
