# Generated by Django 4.2.5 on 2024-02-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_setting_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='current',
        ),
        migrations.AddField(
            model_name='cycle',
            name='current',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
