# Generated by Django 4.2.5 on 2024-02-29 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_setting_current_cycle_current'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='current',
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField()),
                ('settings', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.setting')),
            ],
        ),
    ]
