# Generated by Django 4.2.10 on 2024-02-29 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_cycle_current_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.setting'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='interval',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='setting',
            name='pLen',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
