# Generated by Django 4.2.10 on 2024-03-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_run_settings_alter_setting_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='again',
            field=models.BooleanField(default=False),
        ),
    ]
